
name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install PythonAnywhere CLI
      run: |
        pip install requests
    
    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        PA_DOMAIN: ${{ secrets.PYTHONANYWHERE_DOMAIN }}
      run: |
        # Create deployment script
        cat > deploy.py << 'EOF'
        import requests
        import os
        import time
        import json
        
        API_TOKEN = os.environ['PA_API_TOKEN']
        USERNAME = os.environ['PA_USERNAME']
        DOMAIN = os.environ['PA_DOMAIN']
        
        BASE_URL = 'https://www.pythonanywhere.com/api/v0/user